export type SurveyData = {
  province: string;
  countryOfOrigin1: string;
  countryOfOrigin2: string;
  countryOfOrigin3: string;
  countryOfOrigin4: string;
  spouseCountryOfOrigin: string;
  durationSpouseHasBeenInCanada: string;
  durationUserHasBeenInCanada: string;
  durationChildrenHaveBeenInCanada: string;
  city: string;
  yearUsrMovedToCanada: string;
  yearSpouseMovedToCanada: string;
  yearParentsMovedToCanada: string;
  // usrDurOfStayInCanada: string;
  // familyDurOfStayInCanada: string;
  immigrantStatus: string;
  otherLangsUsedAtHomeYesOrNo: string;
  immigrantStatusOther: string;
  usrGeneration: string;
  usrsHighestEduLvl: string;
  usrsHighestEduLvlOther: string;
  spouseHighestEduLvl: string;
  spouseHighestEduLvlOther: string;
  usrOccupInCanada: string;
  usrOccupInFormerCountry: string;
  mainLangUsedAtHome: string;
  otherLangsUsedAtHome: string;
  userIsAwareOfStrugglingChildInCmmnt: string;
  childInCmmntReceivesSupportFromHome: boolean;
  childInCmmntReceivesSupportFromSchool: boolean;
  childInCmmntReceivesSupportFromCmmnt: boolean;
  userIsAwareOfStrugglingChildInCntry: string;
  childInCountryReceivesSupportFromHome: boolean;
  childInCountryReceivesSupportFromSchool: boolean;
  childInCountryReceivesSupportFromCommunity: boolean;
  usrProficiencyInHomeLngWriting: string;
  usrProficiencyInHomeLngReading: string;
  usrProficiencyInHomeLngSpeaking: string;
  usrProficiencyInEnglishWriting: string;
  usrProficiencyInEnglishReading: string;
  usrProficiencyInEnglishSpeaking: string;
};
